// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mango.services.Data;

#nullable disable

namespace mango.services.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240828175333_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.coupon", b =>
                {
                    b.Property<int>("couponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("couponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinAmount")
                        .HasColumnType("integer");

                    b.HasKey("couponID");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            couponID = 1,
                            CouponCode = "10OFF",
                            DiscountAmount = 10.0,
                            LastUpdated = new DateTime(2024, 8, 28, 17, 53, 32, 766, DateTimeKind.Utc).AddTicks(2170),
                            MinAmount = 20
                        },
                        new
                        {
                            couponID = 2,
                            CouponCode = "20OFF",
                            DiscountAmount = 20.0,
                            LastUpdated = new DateTime(2024, 8, 28, 17, 53, 32, 766, DateTimeKind.Utc).AddTicks(2180),
                            MinAmount = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
